// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA245m8qh5ljFnuPG49loYZr9HbHYHlOCY',
    appId: '1:415374932558:web:49b517653aa33315e3211f',
    messagingSenderId: '415374932558',
    projectId: 'garbage-monitoring-syste-a17d5',
    authDomain: 'garbage-monitoring-syste-a17d5.firebaseapp.com',
    databaseURL: 'https://garbage-monitoring-syste-a17d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'garbage-monitoring-syste-a17d5.appspot.com',
    measurementId: 'G-EQ6VGP07V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ryIvPOjiA9oHOVonJaJ-zux3wpKRHqw',
    appId: '1:415374932558:android:f4f482d90c5da61be3211f',
    messagingSenderId: '415374932558',
    projectId: 'garbage-monitoring-syste-a17d5',
    databaseURL: 'https://garbage-monitoring-syste-a17d5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'garbage-monitoring-syste-a17d5.appspot.com',
  );
}
